const ACTION = {
  GET_PRICE: 'GET_PRICE',
  GET_ARBITAGE_PRICE: 'GET_ARBITAGE_PRICE',
  GET_ARBITAGE_PRICE_LIST: 'GET_ARBITAGE_PRICE_LIST',
  LIST_ALERT: 'LIST_ALERT',
  SLEEP: 'SLEEP',
  CONDITION_ALERT: 'CONDITION_ALERT',
  CANCEL_ALERT: 'CANCEL_ALERT',
  AWAKE: 'AWAKE',
  NUDE: 'NUDE',
  INTERVAL: 'INTERVAL',
  ERROR: 'ERROR',
  CALCULATE: 'CALCULATE',
  CLEAR_INTERVAL: 'CLEAR_INTERVAL'
}

module.exports = ACTION
