const ACTION = {
  GET_PRICE: 'GET_PRICE',
  GET_ARBITAGE_PRICE: 'GET_ARBITAGE_PRICE',
  SLEEP: 'SLEEP',
  AWAKE: 'AWAKE',
  NUDE: 'NUDE',
  INTERVAL: 'INTERVAL',
  ERROR: 'ERROR',
  CALCULATE: 'CALCULATE',
  CLEAR_INTERVAL: 'CLEAR_INTERVAL'
}

module.exports = ACTION
